"""menu_marketplace"""

from alembic import op
import sqlalchemy as sa

revision = "2719b51919c2"
down_revision = "d9db82c80675"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menu_publications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("source_menu_id", sa.Integer(), nullable=True),
        sa.Column("source_version_id", sa.Integer(), nullable=True),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("author_name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=600), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.Column("blocked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["source_menu_id"], ["menus.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["source_version_id"], ["menu_versions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_version_id"),
    )
    with op.batch_alter_table("menu_publications", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_menu_publications_author_id"), ["author_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_menu_publications_created_at"), ["created_at"], unique=False)

    op.create_table(
        "menu_copies",
        sa.Column("publication_id", sa.Integer(), nullable=False),
        sa.Column("household_id", sa.Integer(), nullable=False),
        sa.Column("menu_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["household_id"], ["households.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["menu_id"], ["menus.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["publication_id"],
            ["menu_publications.id"],
        ),
        sa.PrimaryKeyConstraint("publication_id", "household_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menu_copies")
    with op.batch_alter_table("menu_publications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_menu_publications_created_at"))
        batch_op.drop_index(batch_op.f("ix_menu_publications_author_id"))

    op.drop_table("menu_publications")
    # ### end Alembic commands ###
